[package]
name = "spectre-gtk"
version = "0.1.0"
authors = ["toger5 <toger5@hotmail.de>"]
edition = "2018"
build = "build-aux/build.rs"

[profile.dev]
rpath = true

[dependencies]
num = "0.2"
dirs = "2.0.2"
num-traits = "0.2"
num-derive = "0.2"
pango = "0.9.1"
libc = "0.2.91"

[dependencies.gtk]
package = "gtk4"
git = "https://github.com/gtk-rs/gtk4-rs"

[dependencies.gdk]
git = "https://github.com/gtk-rs/gtk4-rs/"
package = "gdk4"

[dependencies.adw]
package = "libadwaita"
git = "https://gitlab.gnome.org/bilelmoussaoui/libadwaita-rs.git"

[build-dependencies]
bindgen = "0.57"
cc = "1.0.67"