[package]
name = "spectre-gtk"
version = "0.1.0"
authors = ["toger5 <toger5@hotmail.de>"]
edition = "2018"
build = "build-aux/build.rs"

[profile.dev]
rpath = true

[dependencies]
num = "0.2"
dirs = "2.0.2"
num-traits = "0.2"
num-derive = "0.2"
pango = "0.9.1"
libc = "0.2.91"

[dependencies.gtk]
version = "0.9.2"
features = ["v3_24"]

[dependencies.gio]
version = ""
features = ["v2_44"]

[build-dependencies]
bindgen = "0.57"
cc = "1.0.67"